import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const MEETING_TYPE_LABELS = {
  intro: 'פגישת היכרות',
  qualifying: 'פגישת סינון',
  quote_presentation: 'הצגת הצעת מחיר',
  stage_review: 'סקירת שלב',
  site_visit: 'ביקור באתר',
  zoom: 'פגישת זום',
  design_approval: 'אישור עיצוב',
};

function generateToken() {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let token = '';
  for (let i = 0; i < 32; i++) {
    token += chars[Math.floor(Math.random() * chars.length)];
  }
  return token;
}

Deno.serve(async (req) => {
  try {
    const body = await req.json();
    const { data, event } = body;

    if (!data || event?.type !== 'create') {
      return Response.json({ status: 'skipped', reason: 'not a create event' });
    }

    const base44 = createClientFromRequest(req);

    // Always generate a scheduling_token for new meetings
    const schedulingToken = generateToken();
    await base44.asServiceRole.entities.Meeting.update(event.entity_id, {
      scheduling_token: schedulingToken,
    });
    console.log('Scheduling token generated:', schedulingToken);

    // Skip calendar sync if no scheduled date (will sync when date is set later)
    if (!data.scheduled_at) {
      // Send WhatsApp with scheduling link if client has phone
      const clients = await base44.asServiceRole.entities.Client.filter({ id: data.client_id });
      const client = clients[0];
      const meetingLabel = MEETING_TYPE_LABELS[data.type] || data.type || 'פגישה';
      const scheduleUrl = `${Deno.env.get('BASE44_APP_URL') || 'https://app.base44.com'}/schedule?token=${schedulingToken}`;

      // Send WhatsApp if client has phone
      if (client?.phone) {
        let whatsappMsg = `שלום ${client.name} 👋\nנפתחה עבורך ${meetingLabel}.\nנא לבחור מועד נוח בקישור:\n${scheduleUrl}`;
        if (data.type === 'quote_presentation' && data.meeting_price) {
          whatsappMsg += `\n\nמחיר הפגישה: ${data.meeting_price}₪`;
        }

        await base44.asServiceRole.functions.invoke('sendWhatsApp', {
          to: client.phone,
          message: whatsappMsg,
        });

        await base44.asServiceRole.entities.Communication.create({
          client_id: client.id,
          project_id: data.project_id || undefined,
          type: 'whatsapp',
          direction: 'outbound',
          content: `קישור תיאום ${meetingLabel} נשלח ללקוח בווטסאפ`,
          sent_by: 'system',
          status: 'sent',
          channel: 'base44_native',
        });
      }

      // Send Email if client has email (pending Communication — sendEmail picks it up)
      if (client?.email) {
        await base44.asServiceRole.entities.Communication.create({
          client_id: client.id,
          project_id: data.project_id || undefined,
          type: 'email',
          direction: 'outbound',
          content: `שלום ${client.name},\n\nנפתחה עבורך ${meetingLabel}.\nלתיאום מועד נוח לחצ/י על הקישור:\n${scheduleUrl}`,
          sent_by: 'system',
          status: 'pending',
          channel: 'gmail',
        });
      }

      // Create Payment record for quote_presentation with meeting_price
      if (data.type === 'quote_presentation' && data.meeting_price) {
        await base44.asServiceRole.entities.Payment.create({
          client_id: client.id,
          milestone: 'פגישת הצגת הצעת מחיר',
          amount: Number(data.meeting_price),
          due_date: new Date().toISOString().split('T')[0],
          status: 'pending',
        });
        console.log('Payment created for meeting price:', data.meeting_price);
      }

      return Response.json({ status: 'ok', scheduling_token: schedulingToken, reason: 'no scheduled_at, link sent' });
    }

    // Skip sync for auto-generated meetings (created by automation, not by admin)
    // These will be synced when an admin manually updates the scheduled_at
    const createdBy = data.created_by || '';
    const isAutoGenerated = !createdBy || !createdBy.includes('@');
    if (isAutoGenerated) {
      return Response.json({ status: 'skipped', reason: 'auto-generated meeting, will sync on manual update' });
    }

    // Get client details
    const clients = await base44.asServiceRole.entities.Client.filter({ id: data.client_id });
    const client = clients[0];
    if (!client) {
      return Response.json({ status: 'skipped', reason: 'client not found' });
    }

    const meetingLabel = MEETING_TYPE_LABELS[data.type] || data.type || 'פגישה';
    const scheduledAt = new Date(data.scheduled_at);
    const duration = data.duration || 45;
    const endTime = new Date(scheduledAt.getTime() + duration * 60 * 1000);

    // 1. Create Google Calendar event
    const { accessToken } = await base44.asServiceRole.connectors.getConnection('googlecalendar');

    const calendarEvent = {
      summary: `${meetingLabel} — ${client.name}`,
      description: `לקוח: ${client.name}\nטלפון: ${client.phone}${data.summary ? '\nהערות: ' + data.summary : ''}`,
      start: {
        dateTime: scheduledAt.toISOString(),
        timeZone: 'Asia/Jerusalem',
      },
      end: {
        dateTime: endTime.toISOString(),
        timeZone: 'Asia/Jerusalem',
      },
    };

    if (data.location) {
      calendarEvent.location = data.location;
    }

    const calRes = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(calendarEvent),
    });

    const calData = await calRes.json();
    console.log('Calendar event created:', calData.id);

    // Save google_event_id on the meeting record
    await base44.asServiceRole.entities.Meeting.update(event.entity_id, {
      google_event_id: calData.id,
    });

    // 2. Send email invitation to client (if email exists)
    if (client.email) {
      const dateStr = scheduledAt.toLocaleDateString('he-IL', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
      const timeStr = scheduledAt.toLocaleTimeString('he-IL', { hour: '2-digit', minute: '2-digit' });

      const emailBody = `
        <div dir="rtl" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #8B6F47;">שלום ${client.name},</h2>
          <p>נקבעה עבורך פגישה חדשה:</p>
          <table style="border-collapse: collapse; width: 100%; margin: 16px 0;">
            <tr><td style="padding: 8px; font-weight: bold; color: #555;">סוג פגישה:</td><td style="padding: 8px;">${meetingLabel}</td></tr>
            <tr><td style="padding: 8px; font-weight: bold; color: #555;">תאריך:</td><td style="padding: 8px;">${dateStr}</td></tr>
            <tr><td style="padding: 8px; font-weight: bold; color: #555;">שעה:</td><td style="padding: 8px;">${timeStr}</td></tr>
            <tr><td style="padding: 8px; font-weight: bold; color: #555;">משך:</td><td style="padding: 8px;">${duration} דקות</td></tr>
            ${data.location ? `<tr><td style="padding: 8px; font-weight: bold; color: #555;">מיקום:</td><td style="padding: 8px;">${data.location}</td></tr>` : ''}
          </table>
          <p>נשמח לראות אותך! 😊</p>
          <p style="color: #999; font-size: 12px; margin-top: 24px;">הודעה זו נשלחה אוטומטית מהסטודיו</p>
        </div>
      `;

      const subject = `הזמנה ל${meetingLabel} — ${dateStr}`;
      const { accessToken: gmailToken } = await base44.asServiceRole.connectors.getConnection('gmail');
      const subjectEncoded = `=?UTF-8?B?${btoa(unescape(encodeURIComponent(subject)))}?=`;
      const emailRaw = [
        `From: "סטודיו מיכל וולברגר" <me>`,
        `To: ${client.email}`,
        `Subject: ${subjectEncoded}`,
        `MIME-Version: 1.0`,
        `Content-Type: text/html; charset=utf-8`,
        ``,
        emailBody
      ].join('\r\n');
      const raw = btoa(unescape(encodeURIComponent(emailRaw)))
        .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
      const gmailRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${gmailToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ raw }),
      });
      if (!gmailRes.ok) throw new Error(`Gmail error: ${JSON.stringify(await gmailRes.json())}`);

      // 3. Log communication
      await base44.asServiceRole.entities.Communication.create({
        client_id: client.id,
        project_id: data.project_id || undefined,
        type: 'email',
        direction: 'outbound',
        content: `הזמנה ל${meetingLabel} נשלחה ללקוח — ${dateStr} בשעה ${timeStr}`,
        sent_by: 'system',
        status: 'sent',
        channel: 'base44_native',
      });
    }

    // Sync meeting date to linked Quote (if quote_presentation with quote_id)
    if (data.type === 'quote_presentation' && data.quote_id && data.scheduled_at) {
      const meetingDate = scheduledAt.toISOString().split('T')[0];
      await base44.asServiceRole.entities.Quote.update(data.quote_id, {
        meeting_date: meetingDate,
      });
      console.log('Quote meeting_date synced on create:', data.quote_id, meetingDate);
    }

    return Response.json({ status: 'ok', calendar_event_id: calData.id });
  } catch (error) {
    console.error('autoMeetingCreated error:', error.message);

    try {
      const base44 = createClientFromRequest(req);
      const body = await req.json().catch(() => ({}));
      await base44.asServiceRole.entities.Communication.create({
        client_id: body.data?.client_id || '',
        type: 'system_error',
        direction: 'outbound',
        content: `שגיאה באוטומציית יצירת פגישה: ${error.message}`,
        sent_by: 'system',
        status: 'failed',
        channel: 'base44_native',
      });
    } catch (_) { /* ignore logging errors */ }

    return Response.json({ error: error.message }, { status: 500 });
  }
});