import {
  Sparkles, UserPlus, Calendar, UserCheck, FileText, 
  Briefcase, Globe, Layers, CreditCard, PartyPopper, BookOpen
} from 'lucide-react';
import STAGE_TUTORIAL_STEPS from './stageTutorialSteps';

// Convert stage tutorial steps to proper format with icon component
const stageStepsWithIcon = STAGE_TUTORIAL_STEPS.map(step => ({
  ...step,
  icon: BookOpen,
  // Enable practice on all stage steps
  highlightSelector: null,
  navigateTo: step.practiceNavigateTo || '/projects',
  navigateLabel: step.practiceLabel || 'עברי לדף הפרויקטים',
  // Force practice availability
  forcePractice: true,
}));

const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    title: 'ברוכות הבאות למערכת! 🎉',
    content: 'המערכת עוקבת אחר כל לקוח מרגע הכניסה ועד סיום הפרויקט.\nהמדריך יעביר אותך על תרחיש מלא — שלב אחרי שלב.',
    icon: Sparkles,
    iconColor: 'text-amber-600',
    bgColor: 'from-amber-50 to-orange-50',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
  },
  {
    id: 'new-lead',
    title: 'שלב 1 — ליד חדש נכנס',
    content: 'כשמגיע ליד — מכניסים שם, טלפון ומייל.\nהמערכת שולחת ווצאפ אוטומטי ומייצרת משימת מעקב.',
    icon: UserPlus,
    iconColor: 'text-blue-600',
    bgColor: 'from-blue-50 to-indigo-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="add-lead-btn"]',
    navigateTo: '/leads',
    navigateLabel: 'עברי לדף הלידים',
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
  {
    id: 'schedule-meeting',
    title: 'שלב 2 — תיאום פגישת היכרות',
    content: 'יוצרים פגישת היכרות — המערכת שולחת ללקוח וואטסאפ ומייל עם לינק לבחירת מועד.\nכשהלקוח בוחר — נשלח מייל אישור אוטומטי.',
    icon: Calendar,
    iconColor: 'text-green-600',
    bgColor: 'from-green-50 to-emerald-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="add-meeting-btn"]',
    navigateTo: '/meetings',
    navigateLabel: 'עברי לדף הפגישות',
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
  {
    id: 'qualify',
    title: 'שלב 3 — הפיכה למתעניין',
    content: 'מסמנים את פגישת ההיכרות כמבוצעת → נפתח דיאלוג → בוחרים "ממשיך".\nהלקוח הופך למתעניין + נוצרת פגישת הצגת הצעת מחיר + נשלח ללקוח וואטסאפ ומייל עם לינק לבחירת מועד.\nהמערכת גם שולחת מייל עם בקשת תשלום מקדמה (250₪).',
    icon: UserCheck,
    iconColor: 'text-purple-600',
    bgColor: 'from-purple-50 to-violet-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="add-meeting-btn"]',
    navigateTo: '/meetings',
    navigateLabel: 'עברי לדף הפגישות',
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
  {
    id: 'send-quote',
    title: 'שלב 4 — שליחת הצעת מחיר',
    content: 'מסמנים את פגישת הצגת הצעת המחיר כמבוצעת.\nלאחר מכן — מדף הצעות המחיר יוצרים הצעה ומשנים סטטוס ל"נשלחה".\nהמערכת שולחת ללקוח מייל/וואטסאפ עם הקישור להצעה.',
    icon: FileText,
    iconColor: 'text-orange-600',
    bgColor: 'from-orange-50 to-amber-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="add-meeting-btn"]',
    navigateLinks: [
      { path: '/meetings', label: 'עברי לדף הפגישות' },
      { path: '/quotes', label: 'עברי להצעות מחיר' },
    ],
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
  {
    id: 'project-created',
    title: 'שלב 5 — הלקוח אישר → פרויקט נפתח',
    content: 'כשהלקוח אישר את ההצעה — המערכת פותחת פרויקט, יוצרת אבני דרך לתשלום ומעדכנת סטטוס אוטומטית.',
    icon: Briefcase,
    iconColor: 'text-teal-600',
    bgColor: 'from-teal-50 to-cyan-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="add-project-btn"]',
    navigateTo: '/projects',
    navigateLabel: 'עברי לדף הפרויקטים',
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
  {
    id: 'portal',
    title: 'שלב 6 — הפורטל ללקוח',
    content: 'כל לקוח מקבל גישה לפורטל אישי.\nשם הוא יכול לראות את מצב הפרויקט, לאשר קונספט עיצובי, לצפות במסמכים ובהצעות המחיר שלו — בלי לפנות אליך ישירות.',
    icon: Globe,
    iconColor: 'text-pink-600',
    bgColor: 'from-pink-50 to-rose-50',
    position: 'right',
    highlightSelector: '[data-tutorial="portal-btn"]',
    navigateTo: '/clients',
    navigateLabel: 'עברי לדף הלקוחות',
    autoNote: 'הלקוח מקבל לינק לפורטל אוטומטית עם אישור ההצעה',
    tip: 'אפשר לשלוח ללקוח את הקישור לפורטל בכל עת מדף הלקוח',
  },
  {
    id: 'project-stages',
    title: 'שלב 7 — שלבי הפרויקט (1-13)',
    content: 'הפרויקט עובר 13 שלבים — מאפיון ועד ביקורת סיום.\nכל שלב שמסמנים כהושלם מקדם את הפרויקט ויוצר משימה לשלב הבא.\n\n👉 בכרטיסיות הבאות — תרגול מפורט לכל שלב!',
    icon: Layers,
    iconColor: 'text-indigo-600',
    bgColor: 'from-indigo-50 to-blue-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="stage-selector"]',
    navigateTo: '/projects',
    navigateLabel: 'עברי לדף הפרויקטים',
    navigateNote: 'לחצי על פרויקט כדי לראות את לוח השלבים',
  },
  // === 13 כרטיסיות שלבים מפורטות ===
  ...stageStepsWithIcon,
  // === המשך שלבי סיום ===
  {
    id: 'payments',
    title: 'סקירה — תשלומים ומסמכים',
    content: 'כל אבן דרך פיננסית מופיעה כאן.\nניתן לעקוב אחר מה שולם, מה ממתין ולשלוח תזכורת.',
    icon: CreditCard,
    iconColor: 'text-emerald-600',
    bgColor: 'from-emerald-50 to-green-50',
    position: 'bottom',
    highlightSelector: '[data-tutorial="payments-table"]',
    navigateTo: '/payments',
    navigateLabel: 'עברי לדף התשלומים',
  },
  {
    id: 'completion',
    title: 'סיום — הלקוח הפך ל-Completed! 🎊',
    content: 'הלקוח הפך ל-Completed — המערכת שולחת הודעת סיום.\nכל ההיסטוריה נשמרת ונגישה.',
    icon: PartyPopper,
    iconColor: 'text-amber-600',
    bgColor: 'from-amber-50 to-yellow-50',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    autoNote: 'קורה אוטומטית — לא צריך לעשות כלום',
  },
];

export default TUTORIAL_STEPS;